"""add organizations and audience_members tables

Revision ID: 3323d93ad9f1
Revises: ebe1bae8dd8c
Create Date: 2026-07-26 11:09:35.161959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3323d93ad9f1'
down_revision: Union[str, Sequence[str], None] = 'ebe1bae8dd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('audience_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audience_lang_geo', 'audience_members', ['language', 'geography'], unique=False)
    op.create_index(op.f('ix_audience_members_geography'), 'audience_members', ['geography'], unique=False)
    op.create_index(op.f('ix_audience_members_language'), 'audience_members', ['language'], unique=False)
    op.create_index(op.f('ix_audience_members_org_id'), 'audience_members', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audience_members_org_id'), table_name='audience_members')
    op.drop_index(op.f('ix_audience_members_language'), table_name='audience_members')
    op.drop_index(op.f('ix_audience_members_geography'), table_name='audience_members')
    op.drop_index('ix_audience_lang_geo', table_name='audience_members')
    op.drop_table('audience_members')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
