"""add templates table and campaign template_id

Revision ID: ab0a4c4a9170
Revises: 3323d93ad9f1
Create Date: 2026-07-26 16:37:46.033781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0a4c4a9170'
down_revision: Union[str, Sequence[str], None] = '3323d93ad9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('campaign_type', sa.Enum('AWARENESS', 'EMERGENCY', 'EDUCATIONAL', 'ANNOUNCEMENT', name='campaigntype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_campaign_type'), 'templates', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_templates_language'), 'templates', ['language'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('AWARENESS', 'EMERGENCY', 'EDUCATIONAL', 'ANNOUNCEMENT', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'SCHEDULED', 'SENDING', 'COMPLETED', 'FAILED', name='campaignstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('target_filters', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_templates_language'), table_name='templates')
    op.drop_index(op.f('ix_templates_campaign_type'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
