"""add role-specific fields to users table

Revision ID: dcae726bc524
Revises: ab0a4c4a9170
Create Date: 2026-07-29 15:15:50.820745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcae726bc524'
down_revision: Union[str, Sequence[str], None] = 'ab0a4c4a9170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('admin_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('access_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('assigned_region', sa.String(), nullable=True))
    op.add_column('users', sa.Column('shift_timing', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['admin_id'])
    op.create_unique_constraint(None, 'users', ['manager_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'shift_timing')
    op.drop_column('users', 'assigned_region')
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'access_level')
    op.drop_column('users', 'department')
    op.drop_column('users', 'admin_id')
    op.drop_column('users', 'registration_date')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
