"""initial_schema

Revision ID: 31ba053f2749
Revises: 
Create Date: 2026-08-04 20:05:12.892628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ba053f2749'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CAMPAIGN_MANAGER', 'USER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('assigned_region', sa.String(), nullable=True),
    sa.Column('shift_timing', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id'),
    sa.UniqueConstraint('manager_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audience_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audience_lang_geo', 'audience_members', ['language', 'geography'], unique=False)
    op.create_index(op.f('ix_audience_members_geography'), 'audience_members', ['geography'], unique=False)
    op.create_index(op.f('ix_audience_members_language'), 'audience_members', ['language'], unique=False)
    op.create_index(op.f('ix_audience_members_org_id'), 'audience_members', ['org_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('campaign_type', sa.Enum('AWARENESS', 'EMERGENCY', 'EDUCATIONAL', 'ANNOUNCEMENT', name='campaigntype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_campaign_type'), 'templates', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_templates_language'), 'templates', ['language'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('AWARENESS', 'EMERGENCY', 'EDUCATIONAL', 'ANNOUNCEMENT', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'SCHEDULED', 'SENDING', 'COMPLETED', 'FAILED', name='campaignstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('target_filters', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_templates_language'), table_name='templates')
    op.drop_index(op.f('ix_templates_campaign_type'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_audience_members_org_id'), table_name='audience_members')
    op.drop_index(op.f('ix_audience_members_language'), table_name='audience_members')
    op.drop_index(op.f('ix_audience_members_geography'), table_name='audience_members')
    op.drop_index('ix_audience_lang_geo', table_name='audience_members')
    op.drop_table('audience_members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
